---
# OS detection and validation

- name: Gather system facts
  setup:
    gather_subset:
      - "!all"
      - "!min"
      - distribution
      - os_family

- name: Display detected OS information
  debug:
    msg:
      - "Detected OS: {{ ansible_distribution }} {{ ansible_distribution_version }}"
      - "OS Family: {{ ansible_os_family }}"
      - "Architecture: {{ ansible_architecture }}"

- name: Validate OS family is supported
  assert:
    that:
      - ansible_os_family in ['Debian', 'RedHat']
    fail_msg: >
      Unsupported OS family: {{ ansible_os_family }}.
      This role supports Debian and RedHat families only.
    success_msg: "OS family {{ ansible_os_family }} is supported"

- name: Validate Debian-based distribution version
  assert:
    that:
      - (ansible_distribution == 'Ubuntu' and ansible_distribution_major_version | int >= 20) or
        (ansible_distribution == 'Debian' and ansible_distribution_major_version | int >= 11)
    fail_msg: >
      Unsupported {{ ansible_distribution }} version: {{ ansible_distribution_version }}.
      Minimum versions: Ubuntu 20.04, Debian 11
    success_msg: "{{ ansible_distribution }} {{ ansible_distribution_version }} is supported"
  when: ansible_os_family == 'Debian'

- name: Validate RedHat-based distribution version
  assert:
    that:
      - ansible_distribution_major_version | int >= 8
    fail_msg: >
      Unsupported {{ ansible_distribution }} version: {{ ansible_distribution_version }}.
      Minimum version: 8.x
    success_msg: "{{ ansible_distribution }} {{ ansible_distribution_version }} is supported"
  when: ansible_os_family == 'RedHat'
