---
# CPU-only PyTorch installation

- name: Create virtual environment for ComfyUI
  command: python3 -m venv {{ comfyui_venv_dir }}
  args:
    creates: "{{ comfyui_venv_dir }}/bin/activate"
  become: true
  become_user: "{{ comfyui_user }}"

- name: Upgrade pip in virtual environment
  pip:
    name:
      - pip
      - setuptools
      - wheel
    state: latest
    virtualenv: "{{ comfyui_venv_dir }}"
  become: true
  become_user: "{{ comfyui_user }}"

- name: Install CPU-only PyTorch
  pip:
    name:
      - torch
      - torchvision
      - torchaudio
    extra_args: "--index-url https://download.pytorch.org/whl/cpu"
    virtualenv: "{{ comfyui_venv_dir }}"
  become: true
  become_user: "{{ comfyui_user }}"

- name: Verify PyTorch installation
  shell: |
    source {{ comfyui_venv_dir }}/bin/activate
    python -c "import torch; print(f'PyTorch Version: {torch.__version__}'); print('Running in CPU-only mode')"
  args:
    executable: /bin/bash
  register: cpu_check
  changed_when: false
  become: true
  become_user: "{{ comfyui_user }}"

- name: Display PyTorch verification
  debug:
    msg: "{{ cpu_check.stdout_lines }}"
