---
# ROCm-enabled PyTorch installation

- name: Create virtual environment for ComfyUI
  command: python3 -m venv {{ comfyui_venv_dir }}
  args:
    creates: "{{ comfyui_venv_dir }}/bin/activate"
  become: true
  become_user: "{{ comfyui_user }}"

- name: Upgrade pip in virtual environment
  pip:
    name:
      - pip
      - setuptools
      - wheel
    state: latest
    virtualenv: "{{ comfyui_venv_dir }}"
  become: true
  become_user: "{{ comfyui_user }}"

- name: Install PyTorch with ROCm support
  pip:
    name:
      - torch
      - torchvision
      - torchaudio
    extra_args: "--index-url https://download.pytorch.org/whl/{{ pytorch_rocm_version }}"
    virtualenv: "{{ comfyui_venv_dir }}"
  become: true
  become_user: "{{ comfyui_user }}"

- name: Verify ROCm is available in PyTorch
  shell: |
    source {{ comfyui_venv_dir }}/bin/activate
    python -c "import torch; print(f'ROCm Available: {torch.cuda.is_available()}'); print(f'ROCm Devices: {torch.cuda.device_count()}')"
  args:
    executable: /bin/bash
  register: rocm_check
  changed_when: false
  become: true
  become_user: "{{ comfyui_user }}"

- name: Display ROCm verification
  debug:
    msg: "{{ rocm_check.stdout_lines }}"
